version: '3.9'
services:
  video_uploader:
    build: .
    restart: always
    expose:
      - "8080"
    depends_on:
      - mongo_video_metadata
    environment:
      MONGO_URI: "mongodb://root:root@mongo_video_metadata:27017"
  mongo_video_metadata:
      image: mongo:latest
      restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: root
        MONGO_INITDB_DATABASE: video_db
      expose:
        - "27017"
      volumes:
        - video_metadata:/data/db
volumes:
  video_metadata:
