name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-test-dockerhub:
    runs-on: ubuntu-latest
    env:
      ENV: testing

    steps:
      - uses: actions/checkout@v3

      - name: Build and start services with docker-compose
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml up -d

      - name: Run tests with pytest
        run: docker-compose -f docker-compose.yml exec -T video_uploader pytest

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build Docker image
        run: docker build . -t ${{ secrets.DOCKERHUB_USERNAME }}/ba-video-uploader

      - name: Push Docker image to registry
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/ba-video-uploader
